source 'https://rubygems.org'

gem 'jekyll-theme-hydejack', '~> 9.1', '>= 9.1.6'
gem 'jekyll-sass-converter', '~> 2.0'
gem 'liquid-md5'
gem 'jekyll-tagging'
gem 'jekyll-default-layout'
gem 'jekyll-feed'
gem 'jekyll-optional-front-matter'
gem 'jekyll-paginate'
gem 'jekyll-readme-index'
gem 'jekyll-redirect-from'
gem 'jekyll-relative-links'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll-titles-from-headings'
gem 'jekyll-last-modified-at'